services:
  glances-exporter:
    build: .
    container_name: glances-exporter
    restart: unless-stopped
    network_mode: host
    environment:
      - GLANCES_URL=http://localhost:61208
      - PORT=9101
