services:
  nest-exporter:
    build: .
    container_name: nest-exporter
    restart: unless-stopped
    ports:
      - "9102:9102"
    env_file:
      - .env
    environment:
      - PORT=9102
      - POLL_INTERVAL=60
